### ISSUE TITLE
Censorship

### ISSUE THREAD

**Issue by ekr** [IRTF-HRPC/draft-guidelines#8]
The censorship section needs some work, in that it conflates
a number of different concepts:

- Protocol mechanisms which facilitate or mititate blocking
  (e.g., SNI and ECH respectively).

- Protocol architectures which might or might not facilitate
  blocking (e.g., centralized versus decentralized architectures
  in the discussion of HTTP).

- User awareness of when blocking is happening

- User identification (MAC addresses in IPv6)

I think the last of these should be moved to the section(s) on
anonymity and pseudonymity as they apply even in non-censorship
contexts.

Each of the other points seems like it deserves more text
and to be more clearly separated out. I think the first and
third are pretty straightforward (and you might point to the
PEARG drafts to minimize work). The second seems largely
missing here and I think requires some care because we don't
really know too much about how censorship resistant these
systems are, but I think there's some evidence here with
Bittorrent and the like.

**Comment by mallory** [comment]
Noting that already the draft links to a deeper dive on censorship in the PEARG but probably the citation needs updating:

> draft-irtf-pearg-censorship: title: A Survey of Worldwide Censorship Techniques date: 2020 author: - ins: J. Hall - ins: M. Aaron - ins: S. Adams - ins: B. Jones - ins: N. Feamster target: https://tools.ietf.org/html/draft-irtf-pearg-censorship

**Comment by gurshabad** [comment]
Ekr, thanks. I'm sensing that you think that the first (Protocol mechanisms which facilitate blocking) and third point (user awareness of blocking) are fine. We expanded on this section a bit after your initial review, explaining censorship based on DNS, SNI, etc.. As Mallory has said, the draft links to pearg-censorship which has a good treatment of the first point. 

I agree with you that your last bullet, user identification (MAC addresses in IPv6), can be moved because it may be more relevant to other sections. Please feel free to file a PR.

I am not exactly sure what you mean by the second bullet point. But happy to discuss that further.

**Comment by ekr** [comment]
By the second point I mean "protocol architectures that facilitate censorship".

**Comment by gurshabad** [comment]
Coming back to this: I agree that this section should focus on identifiers of content, not users. To reflect that, I've edited the text and moved the IPv6 reference to be under pseudonymity.

Currently then, the section focuses mainly on "Protocol mechanisms which facilitate or mititate blocking (e.g., SNI and ECH respectively)." 

I agree that there is no focused discussion on "Protocol architectures which might or might not facilitate blocking (e.g., centralized versus decentralized architectures in the discussion of HTTP)" or BitTorrent-type architectures, etc. I'd welcome a PR on that front. The text does not have to be conclusive, especially if the group does not think there is enough evidence of how censorship resistant those systems are.

**Comment by ekr** [comment]
Sounds like we are roughly on the same page. If you'd like to assign this
to me, I will take a stab at a PR.
